def work():
    f = open("files/out/singleHash/outBinRand.txt", "r")
    print("single Hash rand len " + str(len(f.read())))
    f.close()
    f = open("files/out/singleHash/outBin.txt", "r")
    print("single Hash len " + str(len(f.read())))
    f.close()

    f = open("files/out/doubleHash/outBinRand.txt", "r")
    print("double Hash rand len " + str(len(f.read())))
    f.close()
    f = open("files/out/doubleHash/outBin.txt", "r")
    print("double Hash len " + str(len(f.read())))
    f.close()

    f = open("files/out/RossWilliams/outBinRand.txt", "r")
    print("Ross williams rand len " + str(len(f.read())))
    f.close()
    f = open("files/out/RossWilliams/outBin.txt", "r")
    print("Ross williams len " + str(len(f.read())))
    f.close()

    f = open("files/out/doubleRoss/outBinRand.txt", "r")
    print("double Ross rand len " + str(len(f.read())))
    f.close()
    f = open("files/out/doubleRoss/outBin.txt", "r")
    print("double Ross len " + str(len(f.read())))
    f.close()

    f = open("files/out/doublePenta/outBinRand.txt", "r")
    print("doublePenta rand len " + str(len(f.read())))
    f.close()
    f = open("files/out/doublePenta/outBin.txt", "r")
    print("doublePenta len " + str(len(f.read())))
    f.close()

    f = open("files/out/singlePenta/outBinRand.txt", "r")
    print("singlePenta rand len " + str(len(f.read())))
    f.close()
    f = open("files/out/singlePenta/outBin.txt", "r")
    print("singlePenta len " + str(len(f.read())))
    f.close()

    f = open("files/out/doubleQuad/outBinRand.txt", "r")
    print("doubleQuad rand len " + str(len(f.read())))
    f.close()
    f = open("files/out/doubleQuad/outBin.txt", "r")
    print("doubleQuad len " + str(len(f.read())))
    f.close()

    f = open("files/out/singleQuad/outBinRand.txt", "r")
    print("singleQuad rand len " + str(len(f.read())))
    f.close()
    f = open("files/out/singleQuad/outBin.txt", "r")
    print("singleQuad len " + str(len(f.read())))
    f.close()

    f = open("D:/Large Texts/english.200MB.txt", "r")
    print("original file * 8 " + str(8 * len(f.read())))
    f.close()
